using System;
using System.Collections.Generic;
using System.Text;

namespace ObjectDB.Objects
{
    public class UnimplementedObject : ODBObject
    {
        private readonly int ObjectID;

        public UnimplementedObject(int objectID)
        {
            ObjectID = objectID;
        }

        public override string ToString()
        {
            return $"UnimplementedObject (VODBR.dll type name: {GetObjectTypeNameById(ObjectID)})";
        }

        internal override void ParseFromReader(ODBReader reader)
        {
        }

        private static string GetObjectTypeNameById(int object_id)
        {
            switch (object_id)
            {
                case -1:
                    return "ByteFieldImpl";
                case 2:
                    return "VDXVeniceDbImpl";
                case 5:
                    return "VDXAdminDataImpl";
                case 6:
                    return "VDXRequestImpl";
                case 8:
                    return "VDXFunctClassImpl";
                case 10:
                    return "VDXEcuVariantPatternImpl";
                case 0xb:
                    return "VDXMatchingParameterImpl";
                case 0xc:
                    return "VDXComparamSpecImpl";
                case 0xd:
                    return "VDXComparamOldImpl";
                case 0xe:
                    return "VDXDiagServiceImpl";
                case 0xf:
                    return "VDXSingleEcuJobImpl";
                case 0x10:
                    return "VDXParamImpl";
                case 0x11:
                    return "VDXCompuMethodImpl";
                case 0x12:
                    return "VDXUnitImpl";
                case 0x13:
                    return "VDXPhysicalTypeImpl";
                case 0x15:
                    return "VDXDtcDopImpl";
                case 0x17:
                    return "VDXDiagLayerContainerImpl";
                case 0x18:
                    return "VDXDiagCodedTypeImpl";
                case 0x19:
                    return "VDXInternalConstrImpl";
                case 0x1a:
                    return "VDXLimitImpl";
                case 0x1b:
                    return "VDXScaleConstrImpl";
                case 0x1c:
                    return "VDXCompuInternalToPhysImpl";
                case 0x1d:
                    return "VDXCompuScaleImpl";
                case 0x1e:
                    return "VDXCompuRationalCoeffsImpl";
                case 0x1f:
                    return "VDXCompuInverseValueImpl";
                case 0x20:
                    return "VDXCompuConstImpl";
                case 0x22:
                    return "VDXVehicleInfoSpecImpl";
                case 0x23:
                    return "VDXComparamRefImpl";
                case 0x24:
                    return "VDXVehicleInformationImpl";
                case 0x25:
                    return "VDXVehicleConnectorImpl";
                case 0x26:
                    return "VDXVehicleConnectorPinImpl";
                case 0x27:
                    return "VDXPhysicalVehicleLinkImpl";
                case 0x28:
                    return "VDXLogicalLinkImpl";
                case 0x29:
                    return "VDXPhysicalDimensionImpl";
                case 0x2a:
                    return "VDXUnitGroupImpl";
                case 0x2b:
                    return "VDXCompuDefaultValueImpl";
                case 0x2c:
                    return "VDXDataObjectPropImpl";
                case 0x2d:
                    return "VDXProtocolImpl";
                case 0x2e:
                    return "VDXEcuSharedDataImpl";
                case 0x2f:
                    return "VDXBaseVariantImpl";
                case 0x30:
                    return "VDXFunctionalGroupImpl";
                case 0x31:
                    return "VDXEcuVariantImpl";
                case 0x32:
                    return "VDXFlashImpl";
                case 0x33:
                    return "VDXUnitSpecImpl";
                case 0x34:
                    return "VDXDiagDataDictionarySpecImpl";
                case 0x35:
                    return "VDXInfoComponentImpl";
                case 0x37:
                    return "VDXGlobalNegResponseImpl";
                case 0x38:
                    return "VDXPosResponseImpl";
                case 0x39:
                    return "VDXNegResponseImpl";
                case 0x3b:
                    return "VDXMuxImpl";
                case 0x3c:
                    return "VDXStaticListImpl";
                case 0x3d:
                    return "VDXEnvDataDescImpl";
                case 0x3e:
                    return "VDXStaticFieldImpl";
                case 0x3f:
                    return "VDXDynamicEndmarkerFieldImpl";
                case 0x40:
                    return "VDXDynamicLengthFieldImpl";
                case 0x42:
                    return "VDXEndOfPduFieldImpl";
                case 0x43:
                    return "VDXStructureImpl";
                case 0x44:
                    return "VDXCompanyDataImpl";
                case 0x45:
                    return "VDXVImpl";
                case 0x46:
                    return "VDXVtImpl";
                case 0x55:
                    return "VDXEnvDataImpl";
                case 0x56:
                    return "VDXSwitchKeyImpl";
                case 0x57:
                    return "VDXCaseImpl";
                case 0x58:
                    return "VDXDefaultCaseImpl";
                case 0x5b:
                    return "VDXSnrefImpl";
                case 0x5c:
                    return "VDXDynEndDopRefImpl";
                case 0x5d:
                    return "VDXParentRefImpl";
                case 0x5e:
                    return "VDXNotInheritedDiagCommImpl";
                case 0x5f:
                    return "VDXNotInheritedVariableImpl";
                case 0x60:
                    return "VDXDetermineNumberOfItemsImpl";
                case 0x61:
                    return "VDXCanMessageImpl";
                case 99:
                    return "VDXLinMessageImpl";
                case 100:
                    return "VDXDtcImpl";
                case 0x65:
                    return "VDXOnboardBusImpl";
                case 0x66:
                    return "VDXOnboardNodeImpl";
                case 0x67:
                    return "VDXOnboardDataImpl";
                case 0x68:
                    return "VDXAudienceImpl";
                case 0x69:
                    return "VDXInputParamImpl";
                case 0x6a:
                    return "VDXProgCodeImpl";
                case 0x6b:
                    return "VDXNegOutputParamImpl";
                case 0x6c:
                    return "VDXOutputParamImpl";
                case 0x6d:
                    return "VDXEcuMemImpl";
                case 0x6e:
                    return "VDXMemImpl";
                case 0x6f:
                    return "VDXSessionImpl";
                case 0x70:
                    return "VDXDatablockImpl";
                case 0x71:
                    return "VDXFlashdataImpl";
                case 0x72:
                    return "VDXDtcValueImpl";
                case 0x73:
                    return "VDXAllValueImpl";
                case 0x74:
                    return "VDXEnvDatasImpl";
                case 0x75:
                    return "VDXDtcsImpl";
                case 0x76:
                    return "VDXTeamMemberImpl";
                case 0x77:
                    return "VDXTextImpl";
                case 0x78:
                    return "VDXCompanyDocInfoImpl";
                case 0x79:
                    return "VDXDocRevisionImpl";
                case 0x7a:
                    return "VDXModificationOldImpl";
                case 0x7b:
                    return "VDXCompanyRevisionInfoImpl";
                case 0x7c:
                    return "VDXEcuMemConnectorImpl";
                case 0x7d:
                    return "VDXProjectInfoImpl";
                case 0x7e:
                    return "VDXProjectIdentImpl";
                case 0x7f:
                    return "VDXPhysMemImpl";
                case 0x80:
                    return "VDXExpectedIdentImpl";
                case 0x81:
                    return "VDXIdentValueImpl";
                case 0x82:
                    return "VDXChecksumImpl";
                case 0x83:
                    return "VDXSourceEndAddressImpl";
                case 0x84:
                    return "VDXUncompressedSizeImpl";
                case 0x85:
                    return "VDXChecksumResultImpl";
                case 0x86:
                    return "VDXRoleImpl";
                case 0x87:
                    return "VDXFilterImpl";
                case 0x88:
                    return "VDXSegmentImpl";
                case 0x8b:
                    return "VDXTargetAddrOffsetImpl";
                case 0x8e:
                    return "VDXOwnIdentImpl";
                case 0x8f:
                    return "VDXEncryptCompressMethodImpl";
                case 0x90:
                    return "VDXDataformatImpl";
                case 0x93:
                    return "VDXDatafileImpl";
                case 0x94:
                    return "VDXPhysSegmentImpl";
                case 0x97:
                    return "VDXFlashClassImpl";
                case 0x98:
                    return "VDXSessionDescImpl";
                case 0x99:
                    return "VDXIdentDescImpl";
                case 0x9a:
                    return "VDXSdgImpl";
                case 0x9b:
                    return "VDXSdImpl";
                case 0x9c:
                    return "VDXSdgCaptionOldImpl";
                case 0x9d:
                    return "VDXCompanySpecificInfoImpl";
                case 0x9e:
                    return "VDXRelatedDocImpl";
                case 0x9f:
                    return "VDXXdocImpl";
                case 0xa0:
                    return "VDXTableImpl";
                case 0xa1:
                    return "VDXTableRowImpl";
                case 0xa2:
                    return "VDXAccessLevelImpl";
                case 0xa3:
                    return "VDXExternalAccessMethodOldImpl";
                case 0xa4:
                    return "VDXDiagVariableImpl";
                case 0xa5:
                    return "VDXVariableGroupImpl";
                case 0xa6:
                    return "VDXCommRelationImpl";
                case 0xa7:
                    return "VDXMultipleEcuJobSpecImpl";
                case 0xa8:
                    return "VDXSwVariableImpl";
                case 0xad:
                    return "VDXEcuGroupImpl";
                case 0xae:
                    return "VDXMatchingComponentImpl";
                case 0xaf:
                    return "VDXDynDefinedSpecImpl";
                case 0xb0:
                    return "VDXSupportedDynIdImpl";
                case 0xb1:
                    return "VDXAutMethodImpl";
                case 0xb2:
                    return "VDXRelatedServiceRefImpl";
                case 0xb3:
                    return "VDXSelectionTableRefsImpl";
                case 0xb4:
                    return "VDXSecurityImpl";
                case 0xb5:
                    return "VDXSecurityMethodImpl";
                case 0xb6:
                    return "VDXFwChecksumImpl";
                case 0xb7:
                    return "VDXValidityForImpl";
                case 0xb8:
                    return "VDXFwSignatureImpl";
                case 0xb9:
                    return "VDXDescriptionImpl";
                case 0xba:
                    return "VDXPImpl";
                case 0xbb:
                    return "VDXMultipleEcuJobImpl";
                case 0xbd:
                    return "VDXCompuPhysToInternalImpl";
                case 0xbe:
                    return "VDXDiagCommsImpl";
                case 0xbf:
                    return "VDXDiagVariablesImpl";
                case 0xc4:
                    return "VDXCatalogImpl";
                case 0xc5:
                    return "VDXAblockImpl";
                case 0xc6:
                    return "VDXFileImpl";
                case 199:
                    return "VDXFileProxyImpl";
                case 0xca:
                    return "VDXReferenceImpl";
                case 0xce:
                    return "VDXLinkComparamRefImpl";
                case 0xcf:
                    return "VDXRelatedDiagCommRefImpl";
                case 0xd0:
                    return "VDXDynIdDefModeInfoImpl";
                case 0xd1:
                    return "VBXLinMasterImpl";
                case 0xd2:
                    return "VBXLinSlaveImpl";
                case 0xd3:
                    return "VBXCapabilityImpl";
                case 0xd4:
                    return "VBXDoubleImpl";
                case 0xd5:
                    return "VBXRangeImpl";
                case 0xd7:
                    return "VBXSubstitutionFrameImpl";
                case 0xd8:
                    return "VBXFibexImpl";
                case 0xd9:
                    return "VBXProjectImpl";
                case 0xda:
                    return "VBXElementsImpl";
                case 0xdb:
                    return "VBXClusterImpl";
                case 0xdc:
                    return "VBXSignalInstanceImpl";
                case 0xdd:
                    return "VBXManufacturerExtensionImpl";
                case 0xde:
                    return "VBXFrameImpl";
                case 0xdf:
                    return "VBXSignalImpl";
                case 0xe0:
                    return "VBXSubFrameImpl";
                case 0xe1:
                    return "VBXEcuImpl";
                case 0xe2:
                    return "VBXChannelImpl";
                case 0xe3:
                    return "VBXGatewayImpl";
                case 0xe4:
                    return "VBXFunctionImpl";
                case 0xe5:
                    return "VBXCompositeImpl";
                case 0xe6:
                    return "VBXCodingImpl";
                case 0xe7:
                    return "VBXMultiplexerImpl";
                case 0xe8:
                    return "VBXInputPortImpl";
                case 0xe9:
                    return "VBXOutputPortImpl";
                case 0xea:
                    return "VBXDiagnosticAddressesImpl";
                case 0xeb:
                    return "VBXDiagnosticAddressImpl";
                case 0xec:
                    return "VBXControllerImpl";
                case 0xed:
                    return "VBXConnectorImpl";
                case 0xee:
                    return "VBXFrameTriggeringImpl";
                case 0xef:
                    return "VBXTimingsImpl";
                case 0xf0:
                    return "VBXIdentifierImpl";
                case 0xf1:
                    return "VBXInputsImpl";
                case 0xf2:
                    return "VBXProcessingInformationImpl";
                case 0xf3:
                    return "VBXCyclicTimingImpl";
                case 0xf4:
                    return "VBXEventControlledTimingImpl";
                case 0xf5:
                    return "VBXRequestControlledTimingImpl";
                case 0xf6:
                    return "VBXRelativelyScheduledTimingImpl";
                case 0xf7:
                    return "VBXAbsolutelyScheduledTimingImpl";
                case 0xf8:
                    return "VBXTimeRangeImpl";
                case 0xf9:
                    return "VBXToleranceImpl";
                case 0xfa:
                    return "VBXActiveConditionImpl";
                case 0xfb:
                    return "VBXSwitchImpl";
                case 0xfc:
                    return "VBXDataImpl";
                case 0xfd:
                    return "VBXCommonLayoutDetailsImpl";
                case 0x101:
                    return "VBXElementRevisionImpl";
                case 0x102:
                    return "VBXProductImpl";
                case 0x106:
                    return "VBXAbsoluteImpl";
                case 0x107:
                    return "VBXRelativeImpl";
                case 0x108:
                    return "VBXSystemTriggerImpl";
                case 0x109:
                    return "VBXSystemStateImpl";
                case 0x10a:
                    return "VBXStartConditionImpl";
                case 0x10b:
                    return "VBXStopConditionImpl";
                case 0x10c:
                    return "VBXSignalTriggerImpl";
                case 0x10d:
                    return "VBXSignalStateImpl";
                case 0x10e:
                    return "VBXSignalProxyImpl";
                case 0x10f:
                    return "VBXSendConditionImpl";
                case 0x110:
                    return "VBXFreeFormatImpl";
                case 0x111:
                    return "VBXByteValueImpl";
                case 0x112:
                    return "VBXSignalsImpl";
                case 0x113:
                    return "VBXEcusImpl";
                case 0x114:
                    return "VBXFunctionsImpl";
                case 0x115:
                    return "VBXFramesImpl";
                case 0x116:
                    return "VBXChannelsImpl";
                case 0x117:
                    return "VBXGatewaysImpl";
                case 0x118:
                    return "VBXCompositesImpl";
                case 0x119:
                    return "VBXClustersImpl";
                case 0x11a:
                    return "VBXConnectorMappingImpl";
                case 0x11b:
                    return "VBXSourceImpl";
                case 0x11c:
                    return "VBXTargetImpl";
                case 0x11e:
                    return "VBXGwDiagnosisDataImpl";
                case 0x11f:
                    return "VBXFrameMappingImpl";
                case 0x120:
                    return "VBXMappingRevisionImpl";
                case 0x121:
                    return "VBXSignalMappingImpl";
                case 0x122:
                    return "VBXOptimisedMappingImpl";
                case 0x124:
                    return "VBXSupportedServiceIdImpl";
                case 0x126:
                    return "VBXKeySlotUsageImpl";
                case 0x127:
                    return "VBXSpeedImpl";
                case 0x12a:
                    return "VBXSignalGroupImpl";
                case 0x12d:
                    return "VBXRequirementsImpl";
                case 0x12e:
                    return "VBXPortReqImpl";
                case 0x12f:
                    return "VBXFunctionReqImpl";
                case 0x131:
                    return "VBXOrderedSignalImpl";
                case 0x132:
                    return "VBXOutputsImpl";
                case 0x133:
                    return "VBXWakeUpImpl";
                case 0x134:
                    return "VBXSpeedValueImpl";
                case 0x135:
                    return "VBXExtentImpl";
                case 0x136:
                    return "VBXFibexCompanyDataImpl";
                case 0x139:
                    return "VBXCompuMethodImpl";
                case 0x13a:
                    return "VBXPhysConstrsImpl";
                case 0x13f:
                    return "VDXStoredObjectImpl";
                case 0x140:
                    return "VBXSoftingExtensionsImpl";
                case 0x141:
                    return "VBXComparamImpl";
                case 0x142:
                    return "VDXAdditionalAudienceImpl";
                case 0x143:
                    return "VDXGroupMemberImpl";
                case 0x145:
                    return "VDXComplexComparamImpl";
                case 0x146:
                    return "VDXComplexPhysicalDefaultValueImpl";
                case 0x148:
                    return "VDXProtStackImpl";
                case 0x149:
                    return "VDXSimpleValueImpl";
                case 0x14a:
                    return "VDXComplexValueImpl";
                case 0x14b:
                    return "VDXComparamSubsetImpl";
                case 0x14c:
                    return "VDXComparamImpl";
                case 0x14d:
                    return "VDXStateChartImpl";
                case 0x14e:
                    return "VDXSubComponentImpl";
                case 0x14f:
                    return "VDXLibraryImpl";
                case 0x150:
                    return "VDXSubComponentPatternImpl";
                case 0x151:
                    return "VDXEnvDataConnectorImpl";
                case 0x152:
                    return "VDXDtcConnectorImpl";
                case 0x153:
                    return "VDXTableRowConnectorImpl";
                case 0x154:
                    return "VDXSubComponentParamConnectorImpl";
                case 0x155:
                    return "VDXInParamIfRefsImpl";
                case 0x156:
                    return "VDXOutParamIfRefsImpl";
                case 0x157:
                    return "VDXStateImpl";
                case 0x158:
                    return "VDXStateTransitionImpl";
                case 0x159:
                    return "VDXPreConditionStateRefImpl";
                case 0x15a:
                    return "VDXStateTransitionRefImpl";
                case 0x15b:
                    return "VDXBaseVariantPatternImpl";
                case 0x15c:
                    return "VDXMatchingBaseVariantParameterImpl";
                case 0x15d:
                    return "VDXPosResponseSuppressableImpl";
                case 0x15e:
                    return "VDXSnrefToTablerowImpl";
                case 0x15f:
                    return "VDXLinkedDtcDopImpl";
                case 0x160:
                    return "VDXExternalAccessMethodImpl";
                case 0x161:
                    return "VDXNotInheritedDopImpl";
                case 0x162:
                    return "VDXNotInheritedTableImpl";
                case 0x163:
                    return "VDXNotInheritedGlobalNegResponseImpl";
                case 0x165:
                    return "VDXNrcCodedValueImpl";
                case 0x166:
                    return "VDXTableDiagCommConnectorImpl";
                case 0x169:
                    return "VDXExternalDocImpl";
                case 0x16a:
                    return "VDXEcuConfigImpl";
                case 0x16b:
                    return "VDXConfigDataDictionarySpecImpl";
                case 0x16c:
                    return "VDXConfigDataImpl";
                case 0x16d:
                    return "VDXValidBaseVariantImpl";
                case 0x16e:
                    return "VDXConfigRecordImpl";
                case 0x16f:
                    return "VDXConfigIdItemImpl";
                case 0x170:
                    return "VDXDiagCommDataConnectorImpl";
                case 0x171:
                    return "VDXOptionItemImpl";
                case 0x172:
                    return "VDXDataIdItemImpl";
                case 0x173:
                    return "VDXSystemItemImpl";
                case 0x174:
                    return "VDXItemValueImpl";
                case 0x176:
                    return "VDXDataRecordImpl";
                case 0x177:
                    return "VDXDataImpl";
                case 0x178:
                    return "VDXReadDiagCommConnectorImpl";
                case 0x179:
                    return "VDXWriteDiagCommConnectorImpl";
                case 0x17a:
                    return "VDXWriteParamValueImpl";
                case 0x17b:
                    return "VDXReadParamValueImpl";
                case 0x17c:
                    return "VDXFunctionDictionaryImpl";
                case 0x17e:
                    return "VDXFunctionNodeImpl";
                case 0x17f:
                    return "VDXFunctionNodeGroupImpl";
                case 0x180:
                    return "VDXFunctionOutParamImpl";
                case 0x181:
                    return "VDXFunctionInParamImpl";
                case 0x182:
                    return "VDXComponentConnectorOldImpl";
                case 0x183:
                    return "VDXFunctionDiagCommConnectorImpl";
                case 0x184:
                    return "VDXDiagObjectConnectorImpl";
                case 0x185:
                    return "VDXSdgCaptionImpl";
                case 0x186:
                    return "VDXModificationImpl";
                case 0x187:
                    return "VDXExternalFileImpl";
                case 0x188:
                    return "VDXComponentConnectorImpl";

                default:
                    return "Unknown";
            }
        }
    }
}
