name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: ODB.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore ODB dependencies
      run: msbuild ODB/ODB.sln /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Build ODBExtract
      run: msbuild ODB/ODBExtract/ODBExtract.csproj /property:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Upload the completed build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ODBExtract (Windows, ZIP)
        path: ODB/ODBExtract/bin/Release/net5.0
